### ISSUE TITLE
Edit size/format in "If your group wants to ___, we've got you covered"

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#52] opened 2022-06-23 18:21 UTC
The way this is so large on the left and right, and the center wraps a lot doesn't look so clear/clean to me- there's lots of empty space and also crowded space; 

also it doesn't all fit on 1 page unless i zoom out to 50%

![image](https://user-images.githubusercontent.com/64920686/175366405-c1cece6b-2ae3-4761-93dd-05618aef4de0.png)

Not sure of exact edits that could be made. Possible suggestions: 
- freeze left and right columns so that if you must scroll, at least you can see the whole sentence
- expand the width of the middle column so there aren't as many line breaks per bullet point

**Comment by jboolean** [comment] 2022-06-24 16:27
What size screen is this on?

@Memo-Es

**Comment by Memo-Es** [comment] 2022-06-28 02:12
I already edited this in the design file, waiting for the fix in production.
Reference:
<img width="1291" alt="Screen Shot on 2022-06-27 at 21-10-33" src="https://user-images.githubusercontent.com/49539954/176076431-32f3327d-e6e7-4ffd-86ac-df684629a699.png">

cc @jboolean

**Comment by jboolean** [comment] 2022-07-02 16:02
Duplicate of #28

**Closed by jboolean** 2022-07-02 16:02 UTC
